# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnnotationGui.ui'
#
# Created: Tue Oct 17 15:50:52 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setMouseTracking(False)
        self.CentralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CentralWidget.sizePolicy().hasHeightForWidth())
        self.CentralWidget.setSizePolicy(sizePolicy)
        self.CentralWidget.setMouseTracking(False)
        self.CentralWidget.setObjectName("CentralWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.CentralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FrameLeft = QtGui.QFrame(self.CentralWidget)
        self.FrameLeft.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameLeft.setFrameShadow(QtGui.QFrame.Plain)
        self.FrameLeft.setLineWidth(0)
        self.FrameLeft.setObjectName("FrameLeft")
        self.verticalLayout = QtGui.QVBoxLayout(self.FrameLeft)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlotDomain = QtGui.QVBoxLayout()
        self.PlotDomain.setObjectName("PlotDomain")
        self.verticalLayout.addLayout(self.PlotDomain)
        self.TimeScroll = QtGui.QScrollBar(self.FrameLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeScroll.sizePolicy().hasHeightForWidth())
        self.TimeScroll.setSizePolicy(sizePolicy)
        self.TimeScroll.setMaximum(0)
        self.TimeScroll.setProperty("value", 0)
        self.TimeScroll.setSliderPosition(0)
        self.TimeScroll.setTracking(True)
        self.TimeScroll.setOrientation(QtCore.Qt.Horizontal)
        self.TimeScroll.setObjectName("TimeScroll")
        self.verticalLayout.addWidget(self.TimeScroll)
        self.horizontalLayout.addWidget(self.FrameLeft)
        self.FrameRight = QtGui.QFrame(self.CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrameRight.sizePolicy().hasHeightForWidth())
        self.FrameRight.setSizePolicy(sizePolicy)
        self.FrameRight.setMinimumSize(QtCore.QSize(290, 0))
        self.FrameRight.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameRight.setFrameShadow(QtGui.QFrame.Plain)
        self.FrameRight.setLineWidth(0)
        self.FrameRight.setObjectName("FrameRight")
        self.PlayButton = QtGui.QPushButton(self.FrameRight)
        self.PlayButton.setEnabled(False)
        self.PlayButton.setGeometry(QtCore.QRect(10, 330, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.PlayButton.setFont(font)
        self.PlayButton.setObjectName("PlayButton")
        self.PlaySepButton = QtGui.QPushButton(self.FrameRight)
        self.PlaySepButton.setEnabled(False)
        self.PlaySepButton.setGeometry(QtCore.QRect(110, 330, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.PlaySepButton.setFont(font)
        self.PlaySepButton.setObjectName("PlaySepButton")
        self.LoadButton = QtGui.QPushButton(self.FrameRight)
        self.LoadButton.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.LoadButton.setFont(font)
        self.LoadButton.setObjectName("LoadButton")
        self.Information = QtGui.QTableWidget(self.FrameRight)
        self.Information.setGeometry(QtCore.QRect(10, 50, 271, 271))
        self.Information.setAutoScroll(False)
        self.Information.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.Information.setRowCount(6)
        self.Information.setColumnCount(2)
        self.Information.setObjectName("Information")
        self.Information.setColumnCount(2)
        self.Information.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        self.Information.setItem(5, 1, item)
        self.Information.horizontalHeader().setVisible(False)
        self.Information.horizontalHeader().setDefaultSectionSize(133)
        self.Information.horizontalHeader().setHighlightSections(False)
        self.Information.horizontalHeader().setMinimumSectionSize(100)
        self.Information.horizontalHeader().setSortIndicatorShown(False)
        self.Information.horizontalHeader().setStretchLastSection(False)
        self.Information.verticalHeader().setVisible(False)
        self.Information.verticalHeader().setCascadingSectionResizes(False)
        self.Information.verticalHeader().setDefaultSectionSize(40)
        self.Information.verticalHeader().setHighlightSections(False)
        self.Information.verticalHeader().setMinimumSectionSize(25)
        self.Information.verticalHeader().setStretchLastSection(False)
        self.DeleteButton = QtGui.QPushButton(self.FrameRight)
        self.DeleteButton.setEnabled(False)
        self.DeleteButton.setGeometry(QtCore.QRect(100, 410, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setObjectName("DeleteButton")
        self.SaveButton = QtGui.QPushButton(self.FrameRight)
        self.SaveButton.setEnabled(False)
        self.SaveButton.setGeometry(QtCore.QRect(150, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.UndoButton = QtGui.QPushButton(self.FrameRight)
        self.UndoButton.setEnabled(False)
        self.UndoButton.setGeometry(QtCore.QRect(190, 410, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.UndoButton.setFont(font)
        self.UndoButton.setObjectName("UndoButton")
        self.SaveFigureButton = QtGui.QPushButton(self.FrameRight)
        self.SaveFigureButton.setEnabled(False)
        self.SaveFigureButton.setGeometry(QtCore.QRect(10, 480, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.SaveFigureButton.setFont(font)
        self.SaveFigureButton.setObjectName("SaveFigureButton")
        self.ColorButton = QtGui.QPushButton(self.FrameRight)
        self.ColorButton.setEnabled(False)
        self.ColorButton.setGeometry(QtCore.QRect(10, 410, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.ColorButton.setFont(font)
        self.ColorButton.setObjectName("ColorButton")
        self.horizontalLayout.addWidget(self.FrameRight)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.Status = QtGui.QStatusBar(MainWindow)
        self.Status.setObjectName("Status")
        MainWindow.setStatusBar(self.Status)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.PlayButton.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.PlaySepButton.setText(QtGui.QApplication.translate("MainWindow", "Play\n"
"Separation", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.Information.isSortingEnabled()
        self.Information.setSortingEnabled(False)
        self.Information.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "iid", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "sid", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.item(3, 0).setText(QtGui.QApplication.translate("MainWindow", "duration", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.item(4, 0).setText(QtGui.QApplication.translate("MainWindow", "azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.item(5, 0).setText(QtGui.QApplication.translate("MainWindow", "species", None, QtGui.QApplication.UnicodeUTF8))
        self.Information.setSortingEnabled(__sortingEnabled)
        self.DeleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.UndoButton.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveFigureButton.setText(QtGui.QApplication.translate("MainWindow", "Save Figure", None, QtGui.QApplication.UnicodeUTF8))
        self.ColorButton.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))

