# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HARKBirdGui.ui'
#
# Created: Fri Oct 20 10:13:39 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.CentralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CentralWidget.sizePolicy().hasHeightForWidth())
        self.CentralWidget.setSizePolicy(sizePolicy)
        self.CentralWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.CentralWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.CentralWidget.setObjectName("CentralWidget")
        self.TabWidget = QtGui.QTabWidget(self.CentralWidget)
        self.TabWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabWidget.sizePolicy().hasHeightForWidth())
        self.TabWidget.setSizePolicy(sizePolicy)
        self.TabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.TabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TabWidget.setMovable(False)
        self.TabWidget.setObjectName("TabWidget")
        self.RecTab = QtGui.QWidget()
        self.RecTab.setObjectName("RecTab")
        self.RecFrame = QtGui.QFrame(self.RecTab)
        self.RecFrame.setGeometry(QtCore.QRect(10, 10, 381, 531))
        self.RecFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.RecFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.RecFrame.setLineWidth(0)
        self.RecFrame.setMidLineWidth(0)
        self.RecFrame.setObjectName("RecFrame")
        self.RecList = QtGui.QListWidget(self.RecFrame)
        self.RecList.setGeometry(QtCore.QRect(10, 70, 361, 451))
        self.RecList.setObjectName("RecList")
        self.RecFolderPath = QtGui.QLineEdit(self.RecFrame)
        self.RecFolderPath.setGeometry(QtCore.QRect(10, 40, 301, 27))
        self.RecFolderPath.setMinimumSize(QtCore.QSize(301, 0))
        self.RecFolderPath.setPlaceholderText("")
        self.RecFolderPath.setObjectName("RecFolderPath")
        self.RecFolderBrowser = QtGui.QToolButton(self.RecFrame)
        self.RecFolderBrowser.setGeometry(QtCore.QRect(310, 40, 27, 27))
        self.RecFolderBrowser.setObjectName("RecFolderBrowser")
        self.RecLable0 = QtGui.QLabel(self.RecFrame)
        self.RecLable0.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.RecLable0.setFont(font)
        self.RecLable0.setObjectName("RecLable0")
        self.RecReload = QtGui.QPushButton(self.RecFrame)
        self.RecReload.setGeometry(QtCore.QRect(340, 40, 27, 27))
        self.RecReload.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecReload.setIcon(icon)
        self.RecReload.setObjectName("RecReload")
        self.RecPlay = QtGui.QPushButton(self.RecTab)
        self.RecPlay.setGeometry(QtCore.QRect(410, 350, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.RecPlay.setFont(font)
        self.RecPlay.setCheckable(False)
        self.RecPlay.setObjectName("RecPlay")
        self.RecLabel1 = QtGui.QLabel(self.RecTab)
        self.RecLabel1.setGeometry(QtCore.QRect(410, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.RecLabel1.setFont(font)
        self.RecLabel1.setObjectName("RecLabel1")
        self.RecFileName = QtGui.QLineEdit(self.RecTab)
        self.RecFileName.setGeometry(QtCore.QRect(410, 50, 171, 27))
        self.RecFileName.setObjectName("RecFileName")
        self.RecLabel2 = QtGui.QLabel(self.RecTab)
        self.RecLabel2.setGeometry(QtCore.QRect(590, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.RecLabel2.setFont(font)
        self.RecLabel2.setObjectName("RecLabel2")
        self.RecPrefix = QtGui.QLineEdit(self.RecTab)
        self.RecPrefix.setGeometry(QtCore.QRect(590, 50, 171, 27))
        self.RecPrefix.setObjectName("RecPrefix")
        self.RecRecording = QtGui.QPushButton(self.RecTab)
        self.RecRecording.setGeometry(QtCore.QRect(410, 250, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.RecRecording.setFont(font)
        self.RecRecording.setCheckable(False)
        self.RecRecording.setChecked(False)
        self.RecRecording.setAutoRepeat(False)
        self.RecRecording.setAutoDefault(False)
        self.RecRecording.setDefault(False)
        self.RecRecording.setFlat(False)
        self.RecRecording.setObjectName("RecRecording")
        self.RecLabel5 = QtGui.QLabel(self.RecTab)
        self.RecLabel5.setGeometry(QtCore.QRect(410, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.RecLabel5.setFont(font)
        self.RecLabel5.setObjectName("RecLabel5")
        self.RecDuration = QtGui.QLineEdit(self.RecTab)
        self.RecDuration.setGeometry(QtCore.QRect(410, 210, 171, 27))
        self.RecDuration.setInputMask("")
        self.RecDuration.setMaxLength(32767)
        self.RecDuration.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.RecDuration.setObjectName("RecDuration")
        self.RecLabel3 = QtGui.QLabel(self.RecTab)
        self.RecLabel3.setGeometry(QtCore.QRect(410, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.RecLabel3.setFont(font)
        self.RecLabel3.setObjectName("RecLabel3")
        self.RecDevice = QtGui.QLineEdit(self.RecTab)
        self.RecDevice.setGeometry(QtCore.QRect(410, 130, 171, 27))
        self.RecDevice.setInputMask("")
        self.RecDevice.setMaxLength(32767)
        self.RecDevice.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.RecDevice.setObjectName("RecDevice")
        self.RecChannel = QtGui.QLineEdit(self.RecTab)
        self.RecChannel.setGeometry(QtCore.QRect(590, 130, 171, 27))
        self.RecChannel.setInputMask("")
        self.RecChannel.setMaxLength(32767)
        self.RecChannel.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.RecChannel.setObjectName("RecChannel")
        self.RecLabel4 = QtGui.QLabel(self.RecTab)
        self.RecLabel4.setGeometry(QtCore.QRect(590, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.RecLabel4.setFont(font)
        self.RecLabel4.setObjectName("RecLabel4")
        self.RecDivide = QtGui.QPushButton(self.RecTab)
        self.RecDivide.setGeometry(QtCore.QRect(410, 450, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.RecDivide.setFont(font)
        self.RecDivide.setCheckable(False)
        self.RecDivide.setObjectName("RecDivide")
        self.RecLabel6 = QtGui.QLabel(self.RecTab)
        self.RecLabel6.setGeometry(QtCore.QRect(590, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.RecLabel6.setFont(font)
        self.RecLabel6.setObjectName("RecLabel6")
        self.RecInterval = QtGui.QLineEdit(self.RecTab)
        self.RecInterval.setGeometry(QtCore.QRect(590, 210, 171, 27))
        self.RecInterval.setInputMask("")
        self.RecInterval.setMaxLength(32767)
        self.RecInterval.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.RecInterval.setObjectName("RecInterval")
        self.TabWidget.addTab(self.RecTab, "")
        self.LocTab = QtGui.QWidget()
        self.LocTab.setObjectName("LocTab")
        self.LocFrame0 = QtGui.QFrame(self.LocTab)
        self.LocFrame0.setGeometry(QtCore.QRect(10, 10, 381, 531))
        self.LocFrame0.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LocFrame0.setFrameShadow(QtGui.QFrame.Plain)
        self.LocFrame0.setLineWidth(0)
        self.LocFrame0.setMidLineWidth(0)
        self.LocFrame0.setObjectName("LocFrame0")
        self.LocWorkDirList = QtGui.QListWidget(self.LocFrame0)
        self.LocWorkDirList.setGeometry(QtCore.QRect(10, 70, 361, 451))
        self.LocWorkDirList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.LocWorkDirList.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.LocWorkDirList.setObjectName("LocWorkDirList")
        self.LocWorkFolderPath = QtGui.QLineEdit(self.LocFrame0)
        self.LocWorkFolderPath.setGeometry(QtCore.QRect(10, 40, 301, 27))
        self.LocWorkFolderPath.setMinimumSize(QtCore.QSize(301, 0))
        self.LocWorkFolderPath.setPlaceholderText("")
        self.LocWorkFolderPath.setObjectName("LocWorkFolderPath")
        self.LocWorkFolderBrowser = QtGui.QToolButton(self.LocFrame0)
        self.LocWorkFolderBrowser.setGeometry(QtCore.QRect(310, 40, 27, 27))
        self.LocWorkFolderBrowser.setObjectName("LocWorkFolderBrowser")
        self.LocWorkLabel0 = QtGui.QLabel(self.LocFrame0)
        self.LocWorkLabel0.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.LocWorkLabel0.setFont(font)
        self.LocWorkLabel0.setObjectName("LocWorkLabel0")
        self.LocWorkDirReload = QtGui.QPushButton(self.LocFrame0)
        self.LocWorkDirReload.setGeometry(QtCore.QRect(340, 40, 27, 27))
        self.LocWorkDirReload.setText("")
        self.LocWorkDirReload.setIcon(icon)
        self.LocWorkDirReload.setObjectName("LocWorkDirReload")
        self.LocFrame1 = QtGui.QFrame(self.LocTab)
        self.LocFrame1.setGeometry(QtCore.QRect(400, 10, 371, 301))
        self.LocFrame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LocFrame1.setFrameShadow(QtGui.QFrame.Raised)
        self.LocFrame1.setObjectName("LocFrame1")
        self.LocParamFolderPath = QtGui.QLineEdit(self.LocFrame1)
        self.LocParamFolderPath.setGeometry(QtCore.QRect(10, 40, 271, 27))
        self.LocParamFolderPath.setAcceptDrops(False)
        self.LocParamFolderPath.setReadOnly(True)
        self.LocParamFolderPath.setPlaceholderText("")
        self.LocParamFolderPath.setObjectName("LocParamFolderPath")
        self.LocParamFolderBrowser = QtGui.QToolButton(self.LocFrame1)
        self.LocParamFolderBrowser.setGeometry(QtCore.QRect(280, 40, 27, 27))
        self.LocParamFolderBrowser.setObjectName("LocParamFolderBrowser")
        self.LocParamLabel0 = QtGui.QLabel(self.LocFrame1)
        self.LocParamLabel0.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.LocParamLabel0.setFont(font)
        self.LocParamLabel0.setTextFormat(QtCore.Qt.PlainText)
        self.LocParamLabel0.setObjectName("LocParamLabel0")
        self.LocParamSave = QtGui.QPushButton(self.LocFrame1)
        self.LocParamSave.setGeometry(QtCore.QRect(310, 40, 51, 27))
        self.LocParamSave.setObjectName("LocParamSave")
        self.LocParamTable = QtGui.QTableWidget(self.LocFrame1)
        self.LocParamTable.setGeometry(QtCore.QRect(5, 71, 361, 221))
        self.LocParamTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.LocParamTable.setColumnCount(3)
        self.LocParamTable.setObjectName("LocParamTable")
        self.LocParamTable.setColumnCount(3)
        self.LocParamTable.setRowCount(0)
        self.LocParamTable.horizontalHeader().setCascadingSectionResizes(False)
        self.LocParamTable.horizontalHeader().setSortIndicatorShown(False)
        self.LocParamTable.horizontalHeader().setStretchLastSection(True)
        self.LocParamTable.verticalHeader().setVisible(False)
        self.LocParamTable.verticalHeader().setHighlightSections(False)
        self.LocParamTable.verticalHeader().setStretchLastSection(False)
        self.LocLabel0 = QtGui.QLabel(self.LocTab)
        self.LocLabel0.setGeometry(QtCore.QRect(400, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.LocLabel0.setFont(font)
        self.LocLabel0.setTextFormat(QtCore.Qt.PlainText)
        self.LocLabel0.setObjectName("LocLabel0")
        self.LocSaveFolderPath = QtGui.QLineEdit(self.LocTab)
        self.LocSaveFolderPath.setGeometry(QtCore.QRect(400, 340, 341, 27))
        self.LocSaveFolderPath.setObjectName("LocSaveFolderPath")
        self.LocSaveFolderBrowser = QtGui.QToolButton(self.LocTab)
        self.LocSaveFolderBrowser.setGeometry(QtCore.QRect(740, 340, 27, 27))
        self.LocSaveFolderBrowser.setObjectName("LocSaveFolderBrowser")
        self.LocLocalize = QtGui.QPushButton(self.LocTab)
        self.LocLocalize.setGeometry(QtCore.QRect(397, 430, 371, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.LocLocalize.setFont(font)
        self.LocLocalize.setObjectName("LocLocalize")
        self.LocLabel1 = QtGui.QLabel(self.LocTab)
        self.LocLabel1.setGeometry(QtCore.QRect(400, 370, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.LocLabel1.setFont(font)
        self.LocLabel1.setTextFormat(QtCore.Qt.PlainText)
        self.LocLabel1.setObjectName("LocLabel1")
        self.LocGain = QtGui.QLineEdit(self.LocTab)
        self.LocGain.setGeometry(QtCore.QRect(400, 400, 41, 27))
        self.LocGain.setObjectName("LocGain")
        self.LocLabel2 = QtGui.QLabel(self.LocTab)
        self.LocLabel2.setGeometry(QtCore.QRect(480, 370, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.LocLabel2.setFont(font)
        self.LocLabel2.setTextFormat(QtCore.Qt.PlainText)
        self.LocLabel2.setObjectName("LocLabel2")
        self.LocConversion = QtGui.QCheckBox(self.LocTab)
        self.LocConversion.setGeometry(QtCore.QRect(480, 400, 221, 22))
        self.LocConversion.setMouseTracking(True)
        self.LocConversion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LocConversion.setObjectName("LocConversion")
        self.TabWidget.addTab(self.LocTab, "")
        self.AnaTab = QtGui.QWidget()
        self.AnaTab.setObjectName("AnaTab")
        self.AnaFlame = QtGui.QFrame(self.AnaTab)
        self.AnaFlame.setGeometry(QtCore.QRect(10, 10, 381, 531))
        self.AnaFlame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.AnaFlame.setFrameShadow(QtGui.QFrame.Plain)
        self.AnaFlame.setLineWidth(0)
        self.AnaFlame.setMidLineWidth(0)
        self.AnaFlame.setObjectName("AnaFlame")
        self.AnaList = QtGui.QListWidget(self.AnaFlame)
        self.AnaList.setGeometry(QtCore.QRect(10, 70, 361, 451))
        self.AnaList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.AnaList.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.AnaList.setObjectName("AnaList")
        self.AnaFolderPath = QtGui.QLineEdit(self.AnaFlame)
        self.AnaFolderPath.setGeometry(QtCore.QRect(10, 40, 301, 27))
        self.AnaFolderPath.setMinimumSize(QtCore.QSize(301, 0))
        self.AnaFolderPath.setPlaceholderText("")
        self.AnaFolderPath.setObjectName("AnaFolderPath")
        self.AnaFolderBrowser = QtGui.QToolButton(self.AnaFlame)
        self.AnaFolderBrowser.setGeometry(QtCore.QRect(310, 40, 27, 27))
        self.AnaFolderBrowser.setObjectName("AnaFolderBrowser")
        self.AnaLabel0 = QtGui.QLabel(self.AnaFlame)
        self.AnaLabel0.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.AnaLabel0.setFont(font)
        self.AnaLabel0.setObjectName("AnaLabel0")
        self.AnaReload = QtGui.QPushButton(self.AnaFlame)
        self.AnaReload.setGeometry(QtCore.QRect(340, 40, 27, 27))
        self.AnaReload.setText("")
        self.AnaReload.setIcon(icon)
        self.AnaReload.setObjectName("AnaReload")
        self.AnaLabel1 = QtGui.QLabel(self.AnaTab)
        self.AnaLabel1.setGeometry(QtCore.QRect(400, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.AnaLabel1.setFont(font)
        self.AnaLabel1.setObjectName("AnaLabel1")
        self.AnaPdfDivNum = QtGui.QLineEdit(self.AnaTab)
        self.AnaPdfDivNum.setGeometry(QtCore.QRect(400, 50, 31, 27))
        self.AnaPdfDivNum.setObjectName("AnaPdfDivNum")
        self.AnaExportFiles = QtGui.QPushButton(self.AnaTab)
        self.AnaExportFiles.setGeometry(QtCore.QRect(400, 90, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.AnaExportFiles.setFont(font)
        self.AnaExportFiles.setObjectName("AnaExportFiles")
        self.AnaLabel2 = QtGui.QLabel(self.AnaTab)
        self.AnaLabel2.setGeometry(QtCore.QRect(620, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.AnaLabel2.setFont(font)
        self.AnaLabel2.setObjectName("AnaLabel2")
        self.AnaDegree = QtGui.QLineEdit(self.AnaTab)
        self.AnaDegree.setGeometry(QtCore.QRect(620, 50, 41, 27))
        self.AnaDegree.setObjectName("AnaDegree")
        self.AnaAnnotation = QtGui.QPushButton(self.AnaTab)
        self.AnaAnnotation.setGeometry(QtCore.QRect(400, 170, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.AnaAnnotation.setFont(font)
        self.AnaAnnotation.setObjectName("AnaAnnotation")
        self.TabWidget.addTab(self.AnaTab, "")
        MainWindow.setCentralWidget(self.CentralWidget)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        self.RecList.setCurrentRow(-1)
        self.LocWorkDirList.setCurrentRow(-1)
        self.AnaList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "HARKBird", None, QtGui.QApplication.UnicodeUTF8))
        self.RecList.setSortingEnabled(True)
        self.RecFolderBrowser.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.RecLable0.setText(QtGui.QApplication.translate("MainWindow", "Working directory", None, QtGui.QApplication.UnicodeUTF8))
        self.RecPlay.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.RecLabel1.setText(QtGui.QApplication.translate("MainWindow", "File name", None, QtGui.QApplication.UnicodeUTF8))
        self.RecFileName.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "YYYYMMDD_HHMMSS.wav", None, QtGui.QApplication.UnicodeUTF8))
        self.RecLabel2.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.RecPrefix.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "location", None, QtGui.QApplication.UnicodeUTF8))
        self.RecRecording.setText(QtGui.QApplication.translate("MainWindow", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.RecLabel5.setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.RecDuration.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "3600", None, QtGui.QApplication.UnicodeUTF8))
        self.RecLabel3.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.RecDevice.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "plughw:1,0", None, QtGui.QApplication.UnicodeUTF8))
        self.RecChannel.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.RecLabel4.setText(QtGui.QApplication.translate("MainWindow", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.RecDivide.setText(QtGui.QApplication.translate("MainWindow", "Divide", None, QtGui.QApplication.UnicodeUTF8))
        self.RecLabel6.setText(QtGui.QApplication.translate("MainWindow", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.RecInterval.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "600", None, QtGui.QApplication.UnicodeUTF8))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.RecTab), QtGui.QApplication.translate("MainWindow", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.LocWorkDirList.setSortingEnabled(True)
        self.LocWorkFolderBrowser.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.LocWorkLabel0.setText(QtGui.QApplication.translate("MainWindow", "Working directory", None, QtGui.QApplication.UnicodeUTF8))
        self.LocParamFolderBrowser.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.LocParamLabel0.setText(QtGui.QApplication.translate("MainWindow", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.LocParamSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.LocLabel0.setText(QtGui.QApplication.translate("MainWindow", "Save directory", None, QtGui.QApplication.UnicodeUTF8))
        self.LocSaveFolderBrowser.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.LocLocalize.setText(QtGui.QApplication.translate("MainWindow", "Localize", None, QtGui.QApplication.UnicodeUTF8))
        self.LocLabel1.setText(QtGui.QApplication.translate("MainWindow", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.LocGain.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.LocLabel2.setText(QtGui.QApplication.translate("MainWindow", "Option", None, QtGui.QApplication.UnicodeUTF8))
        self.LocConversion.setText(QtGui.QApplication.translate("MainWindow", "Converte to 16k wav file", None, QtGui.QApplication.UnicodeUTF8))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.LocTab), QtGui.QApplication.translate("MainWindow", "Localization", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaList.setSortingEnabled(True)
        self.AnaFolderBrowser.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaLabel0.setText(QtGui.QApplication.translate("MainWindow", "Working directory", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaLabel1.setText(QtGui.QApplication.translate("MainWindow", "PDF divided number", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaPdfDivNum.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaExportFiles.setText(QtGui.QApplication.translate("MainWindow", "Export files", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaLabel2.setText(QtGui.QApplication.translate("MainWindow", "Degree", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaDegree.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.AnaAnnotation.setText(QtGui.QApplication.translate("MainWindow", "Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.AnaTab), QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))

import Resource_rc
